name: Update Materials Index

on:
  push:
    branches:
      - main
    paths:
      - 'materials/*.json'
      - '!materials/index.json'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update script
        run: python3 update-materials.py

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet materials/index.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add materials/index.json
          git commit -m "Auto-update materials/index.json"
          git push
